Add README
nocsland/program_engineering pull request #8
Opened 2024-03-17 18:27 UTC by 01Evgeniy

Add README

2024-03-18 02:54 UTC, nocsland requested changes
Необходимо добавить:

1. Ссылку на полный список поддерживаемых языков, можно чтобы не дублировать ссылки можно просто добавить информацию куда-нибудь в строку 10-12. 
2. Добавить информацию о скрипте для автоматического деплоя окружения и запуска приложения.
3.  В зависимости добавить flake8, chardet

2024-03-18 09:25 UTC, ardubovik commented on PJ/README.md
>  Утилита-комбайн, которая органично объединяет в себе несколько других анализаторов кода (pycodestyle, pyflakes и McCabe), а также имеет огромную экосистему плагинов, которые могут добавить к стандарт
Давай вместо " Используемые тулзы" сделаем "Утилиты для анализа кода" а внутри flake8 - в таком случае вообще не нужно описывать что такое flake8. Как смотришь на это?

2024-03-18 10:47 UTC, 01Evgeniy reviewed
Замечания отработал

2024-03-18 10:47 UTC, 01Evgeniy commented on PJ/README.md
>  Утилита-комбайн, которая органично объединяет в себе несколько других анализаторов кода (pycodestyle, pyflakes и McCabe), а также имеет огромную экосистему плагинов, которые могут добавить к стандарт
Поправил, описание все таки предлагаю оставить

2024-03-18 18:50 UTC, nocsland commented on PJ/README.md
Достаточно было указать что полный список поддерживаемых языков находится на странице модели, но так тоже хорошо.

2024-03-18 18:53 UTC, nocsland approved these changes
Один комментарий, для истории, но в целом все хорошо.

2024-03-19 13:28 UTC, srtxtex commented
Нужно добавить информацию о слайдере степени сжатия результата в документацию

2024-03-19 19:17 UTC, ardubovik approved these changes
ок

2024-03-19 20:06 UTC, srtxtex approved these changes
Годно

2024-03-19 20:06 UTC, srtxtex commented on PJ/README.md
> +- Сопилова Н.
Предлагаю добавить для Надежды ее инициал отчества (Сопилова Н. В.)

2024-03-19 20:06 UTC, srtxtex commented on PJ/README.md
> +- Сопилова Н.
Поправлено

2024-03-22 08:53 UTC, merged